POST http://localhost:8080/events
content-type: application/json
//User 1
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NzMwNzg4MDQsInVzZXJJZCI6MX0.7N4mdAV81tr2zJB7nvlEH30Q8VzWMIijrFCNeptLwLY

{
    "name": "Test event",
    "description": "A test event",
    "location": "test location",
    "dateTime": "2026-03-03T12:47:00.000Z"
}