POST http://localhost:8080/events
content-type: application/json

{
    "name": "3Test event",
    "description": "21A test event",
    "location": "2A test location",
    "dateTime": "2026-03-03T12:47:00.000Z"
}